services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    entrypoint: ["/app/bin/docker-entrypoint"]
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - RAILS_ENV=development
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
