ARG RUBY_VERSION=3.4.2
FROM ruby:$RUBY_VERSION

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
    default-mysql-client libjemalloc2 libvips build-essential libyaml-dev libmariadb-dev default-libmysqlclient-dev && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

RUN mkdir /app
WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN bundle install

COPY . ./
